<?php

function client_forms_help($path)
{
    switch ($path) {
        case "admin/help#client_forms":
            return '<p>' . t("Forms to input login data") . '</p>';
            break;
    }
}

function client_forms_menu()
{
    /**
     ***  hook_menu(). ***
     **/

    $items['client_forms/loginuser'] = array(
        'title' => 'Formulario Login',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('loginForm_form'),
        'file' => 'client_forms.api.php',
        'access callback' => TRUE
    );

    $items['client_forms/register'] = array(
        'title' => 'Formulario Registro',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('registerForm_form'),
        'file' => 'client_forms.api.php',
        'access callback' => TRUE
    );

    return $items;
}

function loginForm_form($form, &$form_state) {

    // *** Se usan los accesos al API constantes ***

    $user='apptividades-rtvc-APP';
    $token='055daffdc4c75cdeb6f56b720955b20a';
    $urlConnect = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/connect";

    // *** Se usan los accesos al API constantes ***
    // *** Se crea una una instancia de la clase clientForms() para acceder a los servicios del API con Métodos ***
    $clientForm = new clientForms();

    $clientConnect = $clientForm->connect($user,$token,$urlConnect);
    $connectResult = drupal_json_decode($clientConnect)['result'];

    $connectResultCode = $connectResult['code'];

    // *** Se valida conexión con el API con el Result Code ***
    if ($connectResultCode == 100){


        $form['email'] = array(
            '#type' => 'textfield',
            '#title' => 'Correo Electronico',
            '#size' => 30,
            '#maxlength' => 30,
            '#required' => TRUE,
        );
        $form['password'] = array(
            '#type' => 'password',
            '#title' => 'Contraseña',
            '#size' => 50,
            '#maxlength' => 50,
            '#required' => TRUE,
        );

        $form['submit_button'] = array(
            '#type' => 'submit',
            '#value' => t('Enviar'),
        );

    } else {

        echo("Falló la conexión al API");
        print_r($clientConnect);
    }

    return $form;

}

/**
  ** Se valida el form submit del formulario de Login usando el servicio login del API a través del método login de la instancia clientForms() **
**/
function loginForm_form_submit($form, &$form_state) {

    // *** Se capturan las variables del formulario ***
    $email = $form_state['values']['email'];
    $password = $form_state['values']['password'];

    // *** Se usan los accesos al API constantes ***
    $user='apptividades-rtvc-APP';
    $token='055daffdc4c75cdeb6f56b720955b20a';
    $urlConnect = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/connect";
    $urlLogin = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/login";

    // *** Se crea una una instancia de la clase clientForms() para acceder a los servicios del API con Métodos ***
    $clientForm = new clientForms();

    // *** Se consume el servicio connect con el método connect de clientForms()  ***
    $clientConnect = $clientForm->connect($user,$token,$urlConnect);

    // ** Captura el session_token de la respuesta del servicio connect
    $connectData = drupal_json_decode($clientConnect)['data'];
    $sessionToken = $connectData['session_token'];

    // *** Se consume el servicio login con el método connect de clientForms()  ***
    $clientLogin = $clientForm->login($email,$password,$user,$token,$sessionToken,$urlLogin);

    $loginData = drupal_json_decode($clientLogin)['data'];

    if(isset($loginData['result'])){
        $loginDataResultCode = $loginData['result']['code'];
    } else {
        $loginDataResultCode = drupal_json_decode($clientLogin)['result']['code'];;
    }

    // ** Se valida el Result code del servicio login
    if($loginDataResultCode == 250){
        drupal_goto('client_forms/register');

    } else {
        drupal_set_message($clientLogin);
    }

}

// ** Formulario de Registro **
function registerForm_form($form, &$form_state) {

    $user='apptividades-rtvc-APP';
    $token='055daffdc4c75cdeb6f56b720955b20a';
    $urlConnect = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/connect";

    $clientForm = new clientForms();

    $clientConnect = $clientForm->connect($user,$token,$urlConnect);
    $connectResult = drupal_json_decode($clientConnect)['result'];

    $connectResultCode = $connectResult['code'];

    if ($connectResultCode == 100){


        $form['mail'] = array(
            '#type' => 'textfield',
            '#title' => 'Correo Electronico',
            '#size' => 30,
            '#maxlength' => 30,
            '#required' => TRUE,
        );
        $form['username'] = array(
            '#type' => 'textfield',
            '#title' => 'Nombre de Usuario',
            '#size' => 30,
            '#maxlength' => 30,
            '#required' => TRUE,
        );
        $form['passwd'] = array(
            '#type' => 'password',
            '#title' => 'Contraseña',
            '#size' => 50,
            '#maxlength' => 50,
            '#required' => TRUE,
        );
        $form['name'] = array(
            '#type' => 'textfield',
            '#title' => 'Nombre',
            '#size' => 50,
            '#maxlength' => 50,
            '#required' => TRUE,
        );
        $form['lastname'] = array(
            '#type' => 'textfield',
            '#title' => 'Apellido',
            '#size' => 50,
            '#maxlength' => 50,
            '#required' => TRUE,
        );
        $form['otro_campo'] = array(
            '#type' => 'textfield',
            '#title' => 'Información adicional',
            '#size' => 50,
            '#maxlength' => 50,
            '#required' => FALSE,
        );

        $form['submit_button'] = array(
            '#type' => 'submit',
            '#value' => t('Enviar'),
        );

    } else {

        echo("Falló la conexión al API");
        drupal_set_message($clientConnect);
    }

    return $form;

}

/**
 * Se valida el form submit del formulario de Login usando el servicio setregisteruser del API *
**/

function registerForm_form_submit($form, &$form_state) {

    // *** Se capturan los datos del formulario para enviar como parámetros al servicio setregisteruser ***
    $mail = $form_state['values']['mail'];
    $username = $form_state['values']['username'];
    $passwd = $form_state['values']['passwd'];
    $name = $form_state['values']['name'];
    $lastname = $form_state['values']['lastname'];
    $otro_campo = $form_state['values']['otro_campo'];

    // *** Se usan los accesos al API constantes ***
    $user='apptividades-rtvc-APP';
    $token='055daffdc4c75cdeb6f56b720955b20a';
    $urlConnect = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/connect";
    $urlRegister = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/setregisteruser";
    $urlSetActivity = "http://ec2-52-1-116-91.compute-1.amazonaws.com/api-rtvc/setactivity";

    // Se define el tipo de actividad como constante.
    $type="Logeo por Facebook";

    $clientForm = new clientForms();

    $clientConnect = $clientForm->connect($user,$token,$urlConnect);
    $connectData = drupal_json_decode($clientConnect)['data'];
    $sessionToken = $connectData['session_token'];

    $clientRegister = $clientForm->register($mail,$username,$passwd,$name,$lastname,$otro_campo,$user,$token,$sessionToken,$urlRegister);
    drupal_set_message("RESPUESTA DEL REGISTRO");
    drupal_set_message($clientRegister);

    // Setear actividad usando el método setactivity del API a través del método setActivity de la instancia clientForms()
    $ClientSetActivity = $clientForm->setActivity($user,$token,$sessionToken,$mail,$type,$urlSetActivity);
    // Definir que output se debe mostrar o que acción tomar, por ahora solo se muestra el mismo formulario después del submit
    drupal_set_message("RESPUESTA DEL SET ACTIVITY");
    drupal_set_message($ClientSetActivity);

}